upload:
	mpremote cp AD9833.py :
	#mpremote cp colorful20.png :
	mpremote cp blue.png :
	#mpremote cp multimeter_c6.py :main.py
	mpremote cp multimeter_c6_myEC11.py :main.py

run:
	mpremote reset && mpremote run multimeter_c6_myEC11.py
